### ISSUE TITLE
Add Pattern Tree for Chained Parameters Down a Tree 

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/starterkit-mustache-acidtest#1]
https://github.com/pattern-lab/patternlab-node/issues/539

**Comment by bmuenzenmeyer** [comment]
Confirmed PL Node is off spec, as the left side of the below (PL PHP) is working for pattern group `TEST001`

![image](https://cloud.githubusercontent.com/assets/298435/22310223/2b1b5c5a-e314-11e6-9b5c-f5ceaa19b417.png)

**Comment by e2tha-e** [comment]
Referenced by https://github.com/pattern-lab/patternlab-node/issues/250

**Comment by bmuenzenmeyer** [comment]
PL Node now returns the following output

![image](https://cloud.githubusercontent.com/assets/298435/26235565/9d7d825c-3c31-11e7-8759-0b1705a0a372.png)

I attest that **this** is actually correct, because when rendering only `m`, there is no data passed to it to trip `showMoleculeSubsection` to `true`. That PL PHP renders this constitutes leakage of a downstream pattern (organism) into the rendering of an upstream one (molecule).
